ALTER TABLE members ADD COLUMN removed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE members ADD COLUMN revision BIGINT NOT NULL DEFAULT 0;
CREATE TABLE enterprise_provisions (
 request_key VARCHAR(100) PRIMARY KEY,
 tenant_id VARCHAR(36) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
